# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.12'
after_success:
  - 'export TRAVIS_PASSED=true'

# Coverage report
after_success:
  - npm run report
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: LGB1eLJLp6Fwok+zW2rwHaEpfLqqYRnzQDzHwUkO25tB0L0swHA8al9qnZNLpaS6lA+IdmFduf6puqlL7JFseFqKTlZpO7buiWUlw1fXrdiENDilKxDUsYl8C9AIgAkE6n+n+9B6f39ThLP0asmEALby7XXRnDt5knfkwJQOFCs73McsBmbdLVweQPCxZ6HIxEviJMFOZneK9LulI2CD1yTMDboGB7/T6XCHbFwYR8r6nhmprq9z/nBuUJ9KoK/fbVFjiaYJllmTYfA2s9nDv+LuUOKm76e0kk2m9nuFkcvqUZHZ1+wlzVtEHXQkldVnheFqFXK6kM+3lh+t987hs63Y9EqTH1UlvKZvkBoK2KaWOV4DFGGSLdP3jJ5IOKyAxp9y5Id9+BMQG2mAbMMiPiYXdqqvaFyCo5mWSXHmsJ3I/5XTd2ca1pmnNXUM8NgHyQ9/h92EE4liXArf88BTqHghwEcfzL6Q9KmADrGkRyaLta759p3UZh1DAQ9bg9l9c6LeefQ9Xzw1E506xHJuW+uYArm5SLkCEvi0dqoP7IKWWr8Ht7AumSIb2UPFGKqrt+c81YtQ7YErueq+otoNMTdgmjq2PeRlLyyzxG3e88f4pBeIfjQdICwdwpJBsGVFRN3UGOcqmFbyUPiMdolV67s9mO3QibBAMp7v/dV24tU=
    # SAUCE_TOKENS
    - secure: BX40/X/xgMesx/nxdG3ctEwfSf75upas+XxoL7TV/INoAAFccpHXosxHoRPg30rX1SQh0LFAe9fGn7Wu3udGe3GC7D/1t4fohzAs/7mBqeHj5OEbZxQDTSaZo3+qPWO+YN9gIhR23XlkIYunxB7YOk0G0Jo131i8gGJXh8s6aezxlhh+XD+aamtjgMynCsKXXFG5K/IAQMCfxFniAOsx49ZzphJ86uqyhtPcDE4V4MYb7h3mHIqi84zTNdwAqcW1gyNj5e9TNSr8acQu0gy6RkRx59O2OIDYhLEEdkKdcxI95mD1r/CkotzRQaUxtvSeyOcRQtF393ivarJonLEOFLnHTVEPNHMICj0iyIQlGAV82sssBNBfJxyEd8vpO7JQtDyVWbFCVCzB7+4bxasFV0QBmsyAcki+ihV/5u+M5I+nMMwsMD7y0faACCHs/9wh6a+pDMwUVbtPQYuD2SQwVvamQ/8mMMc5nmw6srwNAplaxhLHRkGzY8Ce5t/q2JUB8yqkgLLps5cn7OahSKPV+fC/9mKreBM8vpU4bZ4SsoFLG0pW9Cr3iOnDYXUOX9+Alr0vCVsSwAncT1kjZW/Cw6i7QkuGaRBz7W8Ycu5v8wj9Af81xzOFHGjPAOsy6tL5UN/+Z9BWV9CKTp0W2HAn63RIOK7NZVt/XL+azTtiBRc=
    - secure: bLoCLZfGDo8VcWWkNHMf2GELnqDJDjEHsEXlYcfjO3rSBVu3bcWf65Ki2m55NKnHF5S4XhodRIYe9fp2JSqiuacYEE2599PnYhvYzGK3faqE3bw/amaaIoLju//lg9TltEAztMFUZ6ykLp/FYkECAZNLMYSAYeVK93bcce6CWfPJmpSndUenrjG1dkMoOZVugBtxXYmVOa29rAhxzcFU7H0s87xhNefLmdVv5HH5TVJVF+jdBWUuUCaNOuLliqeSqxXZemC/XLu2gVOcRjCrC8CZu7KB8+DPOhUdPEEpfIuVEsjfjCS1HmHpRP3k3Gs0pgU9Cclj3SIcMDhtX/d4KulZ99wcxvD2R4qHg+THNpSNre8UZ1nZN3R8yKI9m1WBPkjhvxcBHsJFj+W2vOutop8F9HUYXxCvLrhZrIIa/PKcg3wphY3KMN73WvtmC4ew+f3sr4JI/giC0lNbcjKOkOKC7OheYP2IDKE+Up2BBIcphtvqbgxY/ivJqAnHlEqwBEvx1a122OmRhpWsBjFyo/5Mc0VKNWhjsm5SNp9+l3VLMzl272fkZLbUAPeRXWB3XfdbjlC87N5klSitjzm0DeIGDSXjvr3IT3V3eIH9xAk1a9hA4DR8mBjWPdLpQlIOAgoMj6hSCQ3e4tk7mVHRHqH0V+GpsRp1UzXYZzjfFd4=

# Npm publish options
before_deploy:
  - npm install babel --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: b2AyG90vPkJfJESP+p10jJhf5i3wZRRl91ZxwOZnDLOFhP2wJaoDc+dj90/p6G1WvmOvNpI0nTjE2ew8U7+TL310hWxj4EtbQHpy3i1QPU5u2DfnS9oT7QHPvQt9F6mFWTmjr0yHnd1rdxR58QMlc3GZ9r+COmbfVB4kPDDkm4OcoCtimeWV1ewj1S541GBumeAwn5bpGnAHKO6qXHUW3FO93NuwpdtqlgR9+WmFS5C8qRwjS7DTwdXZ491C8H7H0wVcUonlguD02c20J8uqrWhNgkDoh2oH+JNR6JpwTpdE6OwidJ4z2J5NvY/mbYH0eCHvnl1C0zY2a21mUkYQ5Xf2IwcgIK1GAhfWP2xZ9TsCDa4yPzO0IzIW1TaOfRQwLdbZv1SF5BDEhKEPPyUWUIyM/NpY42FhP8leg72CRtePIK/efPwEx9CK4u/0e2SbcL/BVmsvx1mnAyF+ViHpCJ+KPsEoKm6gTnQxr6KC2QzvSEYDdONJXKTT2w4pak9FKByUYG8lJ704ljaKAckF7lrc7E1kOZGxVbTh6rPuEvgx3bsMS7HABwpUKdZ7XLkDu6xKny/DF4699mkGbC+JdriAlc9bjb/9esCev+5Qq+V9QE35nV1p/TBaoOkLuNQdiUqc+9Q1BOiljmXHNSSwVIzEg5VX69IdZZ3TiU7efbI=

# Cloud testing
after_deploy:
  - npm install
  - npm run setup
  - npm run test-cloud
