#!/usr/bin/env node

// Dependencies
var superserver= require('./').default

// Environment
var port= process.argv.slice(2)[0] || 59798

// Boot
superserver.listen(port,function(){
  console.log('Server running at http://localhost:%s/',port)
})
